#!/usr/bin/env bash
set -euo pipefail

: "${SUPABASE_URL:?SUPABASE_URL is required}"
: "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY is required}"
: "${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID:?ENTERPRISE_EXECUTOR_SIGNING_KEY_ID is required}"
: "${ENTERPRISE_EXECUTOR_SIGNING_SECRET:?ENTERPRISE_EXECUTOR_SIGNING_SECRET is required}"

SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}}"

cat <<EOF
PORT=${PORT:-3001}
ENTERPRISE_CLOUD_PROVIDER=gcp
ENTERPRISE_HOSTNAME=${ENTERPRISE_HOSTNAME:-enterprise.vaultproof.dev}
ENTERPRISE_RUNTIME_TIER=${ENTERPRISE_RUNTIME_TIER:-shared-demo}
ENTERPRISE_EXECUTOR_BASE_URL=${ENTERPRISE_EXECUTOR_BASE_URL:-http://127.0.0.1:3002}
ENTERPRISE_EXECUTOR_SIGNING_KEY_ID=${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID}
ENTERPRISE_EXECUTOR_SIGNING_SECRET=${ENTERPRISE_EXECUTOR_SIGNING_SECRET}
ENTERPRISE_PROXY_TOKEN_SECRET=${ENTERPRISE_PROXY_TOKEN_SECRET:-}
ENTERPRISE_EXECUTE_CONTEXT_CACHE_TTL_MS=${ENTERPRISE_EXECUTE_CONTEXT_CACHE_TTL_MS:-3000}
ENTERPRISE_REQUIRE_ORIGIN_LOCK=${ENTERPRISE_REQUIRE_ORIGIN_LOCK:-false}
ENTERPRISE_ORIGIN_LOCK_HEADER_NAME=${ENTERPRISE_ORIGIN_LOCK_HEADER_NAME:-x-vaultproof-origin-lock}
ENTERPRISE_ORIGIN_LOCK_SECRET=${ENTERPRISE_ORIGIN_LOCK_SECRET:-}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
EOF

if [[ -n "${SUPABASE_ANON_KEY}" ]]; then
  echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}"
fi

if [[ -n "${VAULTPROOF_INTERNAL_ADMIN_HOSTNAME:-}" ]]; then
  echo "VAULTPROOF_INTERNAL_ADMIN_HOSTNAME=${VAULTPROOF_INTERNAL_ADMIN_HOSTNAME}"
fi
