#!/usr/bin/env bash
set -euo pipefail

: "${SUPABASE_URL:?SUPABASE_URL is required}"
: "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY is required}"
: "${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID:?ENTERPRISE_EXECUTOR_SIGNING_KEY_ID is required}"
: "${ENTERPRISE_EXECUTOR_SIGNING_SECRET:?ENTERPRISE_EXECUTOR_SIGNING_SECRET is required}"

SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}}"
MIXPANEL_TOKEN_VALUE="${ENTERPRISE_MIXPANEL_TOKEN:-}"
MIXPANEL_AUTOCAPTURE_VALUE="${ENTERPRISE_MIXPANEL_AUTOCAPTURE:-false}"
MIXPANEL_RECORD_SESSIONS_PERCENT_VALUE="${ENTERPRISE_MIXPANEL_RECORD_SESSIONS_PERCENT:-0}"
INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE="${VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED:-false}"
INTERNAL_ADMIN_APPROVAL_SECRET_VALUE="${VAULTPROOF_INTERNAL_ADMIN_APPROVAL_SECRET:-}"

case "${INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE}" in
  true|false) ;;
  *)
    echo "VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED must be true or false." >&2
    exit 1
    ;;
esac

if [[ "${INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE}" == "true" && -z "${INTERNAL_ADMIN_APPROVAL_SECRET_VALUE}" ]]; then
  echo "VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED=true requires VAULTPROOF_INTERNAL_ADMIN_APPROVAL_SECRET." >&2
  exit 1
fi

cat <<EOF
PORT=${PORT:-3001}
ENTERPRISE_CLOUD_PROVIDER=gcp
ENTERPRISE_HOSTNAME=${ENTERPRISE_HOSTNAME:-enterprise.vaultproof.dev}
ENTERPRISE_RUNTIME_TIER=${ENTERPRISE_RUNTIME_TIER:-shared-demo}
ENTERPRISE_EXECUTOR_BASE_URL=${ENTERPRISE_EXECUTOR_BASE_URL:-http://127.0.0.1:3002}
ENTERPRISE_EXECUTOR_SIGNING_KEY_ID=${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID}
ENTERPRISE_EXECUTOR_SIGNING_SECRET=${ENTERPRISE_EXECUTOR_SIGNING_SECRET}
ENTERPRISE_PROXY_TOKEN_SECRET=${ENTERPRISE_PROXY_TOKEN_SECRET:-}
ENTERPRISE_EXECUTE_CONTEXT_CACHE_TTL_MS=${ENTERPRISE_EXECUTE_CONTEXT_CACHE_TTL_MS:-3000}
ENTERPRISE_REQUIRE_ORIGIN_LOCK=${ENTERPRISE_REQUIRE_ORIGIN_LOCK:-false}
ENTERPRISE_ORIGIN_LOCK_HEADER_NAME=${ENTERPRISE_ORIGIN_LOCK_HEADER_NAME:-x-vaultproof-origin-lock}
ENTERPRISE_ORIGIN_LOCK_SECRET=${ENTERPRISE_ORIGIN_LOCK_SECRET:-}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENTERPRISE_MIXPANEL_TOKEN=${MIXPANEL_TOKEN_VALUE}
ENTERPRISE_MIXPANEL_AUTOCAPTURE=${MIXPANEL_AUTOCAPTURE_VALUE}
ENTERPRISE_MIXPANEL_RECORD_SESSIONS_PERCENT=${MIXPANEL_RECORD_SESSIONS_PERCENT_VALUE}
VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED=${INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE}
VAULTPROOF_INTERNAL_ADMIN_APPROVAL_SECRET=${INTERNAL_ADMIN_APPROVAL_SECRET_VALUE}
EOF

if [[ -n "${SUPABASE_ANON_KEY}" ]]; then
  echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}"
fi

if [[ -n "${VAULTPROOF_INTERNAL_ADMIN_HOSTNAME:-}" ]]; then
  echo "VAULTPROOF_INTERNAL_ADMIN_HOSTNAME=${VAULTPROOF_INTERNAL_ADMIN_HOSTNAME}"
fi

if [[ -n "${VAULTPROOF_INTERNAL_ADMIN_EMAILS:-}" ]]; then
  echo "VAULTPROOF_INTERNAL_ADMIN_EMAILS=${VAULTPROOF_INTERNAL_ADMIN_EMAILS}"
fi

if [[ -n "${VAULTPROOF_INTERNAL_ADMIN_DOMAINS:-}" ]]; then
  echo "VAULTPROOF_INTERNAL_ADMIN_DOMAINS=${VAULTPROOF_INTERNAL_ADMIN_DOMAINS}"
fi
