#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-vaultproof-prod}"
LOCATION="${LOCATION:-us-central1}"
ZONE="${ZONE:-us-central1-a}"
KEY_RING="${KEY_RING:-vaultproof-runtime}"
KMS_KEY="${KMS_KEY:-vaultproof-unwrap}"
VM_NAME="${VM_NAME:-vaultproof-enterprise-runtime-1}"
EXECUTOR_SA="${EXECUTOR_SA:-vaultproof-executor@${PROJECT_ID}.iam.gserviceaccount.com}"
GCP_KMS_CRYPTO_KEY_RESOURCE="${GCP_KMS_CRYPTO_KEY_RESOURCE:-${CUSTOMER_GCP_KMS_CRYPTO_KEY_RESOURCE:-}}"
GCP_KMS_KEY_VERSION="${GCP_KMS_KEY_VERSION:-${CUSTOMER_GCP_KMS_KEY_VERSION:-}}"

: "${SUPABASE_URL:?SUPABASE_URL is required}"
: "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY is required}"
: "${ENTERPRISE_EXECUTOR_ACCEPTED_SIGNING_KEYS:?ENTERPRISE_EXECUTOR_ACCEPTED_SIGNING_KEYS is required}"
: "${GCP_KMS_ENCRYPTED_VAULT_UNWRAP_KEY_BASE64:?GCP_KMS_ENCRYPTED_VAULT_UNWRAP_KEY_BASE64 is required}"
: "${GCP_KMS_KEY_VERSION:?GCP_KMS_KEY_VERSION is required}"
: "${VAULTPROOF_EXECUTOR_BUILD_DIGEST:?VAULTPROOF_EXECUTOR_BUILD_DIGEST is required}"
: "${GCP_ATTESTATION_TOKEN_HASH:?GCP_ATTESTATION_TOKEN_HASH is required}"
: "${GCP_MEASUREMENT_SUMMARY:?GCP_MEASUREMENT_SUMMARY is required}"

cat <<EOF
PORT=${PORT:-3002}
ENTERPRISE_CLOUD_PROVIDER=gcp
VAULTPROOF_EXECUTOR_MODE=confidential
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENTERPRISE_EXECUTOR_ACCEPTED_SIGNING_KEYS=${ENTERPRISE_EXECUTOR_ACCEPTED_SIGNING_KEYS}
GCP_PROJECT_ID=${PROJECT_ID}
GCP_LOCATION=${LOCATION}
GCP_KMS_KEY_RING=${KEY_RING}
GCP_KMS_KEY_NAME=${KMS_KEY}
GCP_KMS_KEY_VERSION=${GCP_KMS_KEY_VERSION}
GCP_KMS_PROTECTION_LEVEL=${GCP_KMS_PROTECTION_LEVEL:-SOFTWARE}
GCP_KMS_CRYPTO_KEY_RESOURCE=${GCP_KMS_CRYPTO_KEY_RESOURCE}
GCP_KMS_ENCRYPTED_VAULT_UNWRAP_KEY_BASE64=${GCP_KMS_ENCRYPTED_VAULT_UNWRAP_KEY_BASE64}
GCP_KMS_CACHE_TTL_MS=${GCP_KMS_CACHE_TTL_MS:-60000}
VAULTPROOF_EXECUTOR_BUILD_DIGEST=${VAULTPROOF_EXECUTOR_BUILD_DIGEST}
GCP_ATTESTATION_TOKEN_HASH=${GCP_ATTESTATION_TOKEN_HASH}
GCP_CONFIDENTIAL_VM_RESOURCE_ID=${GCP_CONFIDENTIAL_VM_RESOURCE_ID:-projects/${PROJECT_ID}/zones/${ZONE}/instances/${VM_NAME}}
GCP_MEASUREMENT_SUMMARY=${GCP_MEASUREMENT_SUMMARY}
GCP_SECURE_BOOT=${GCP_SECURE_BOOT:-true}
GCP_ATTESTATION_EXPECTED_IMAGE_DIGEST=${GCP_ATTESTATION_EXPECTED_IMAGE_DIGEST:-${VAULTPROOF_EXECUTOR_BUILD_DIGEST}}
GCP_SERVICE_ACCOUNT_EMAIL=${GCP_SERVICE_ACCOUNT_EMAIL:-${EXECUTOR_SA}}
GCP_ATTESTATION_TYPE=${GCP_ATTESTATION_TYPE:-google-cloud-attestation}
GCP_ISOLATION_PROVIDER=${GCP_ISOLATION_PROVIDER:-gcp-confidential-vm}
EOF
