/**
 * .env rewriting — swap real keys for the VaultProof project ID, inject
 * provider BASE_URL lines where the SDK supports env-var override, and
 * create a timestamped backup first.
 *
 * Universal version: BASE_URL placement is driven by providers.json
 * (base_url_env_var + base_url_path_suffix). Providers without a base-URL
 * env var (e.g. GitHub, Linear, Resend) just get their key swapped — the
 * user manually points their client at `https://init.vaultproof.dev/p/:slug`.
 */
import fs from 'node:fs';
import type { Finding } from './scan.js';
import type { ProviderSpec } from './providers.js';

export interface RewriteOptions {
  projectId: string;
  proxyBaseUrl: string;
}

function backupPath(envPath: string): string {
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  return `${envPath}.backup.${ts}`;
}

export function backupEnvFile(envPath: string): string {
  const dest = backupPath(envPath);
  fs.copyFileSync(envPath, dest);
  return dest;
}

export function rewriteEnvFile(
  envPath: string,
  findings: Finding[],
  opts: RewriteOptions,
): { rewritten: number; backupPath: string; manualNotes: string[] } {
  if (!fs.existsSync(envPath)) return { rewritten: 0, backupPath: '', manualNotes: [] };

  const relevant = findings.filter((f) => f.file === envPath);
  if (relevant.length === 0) return { rewritten: 0, backupPath: '', manualNotes: [] };

  const backup = backupEnvFile(envPath);
  const original = fs.readFileSync(envPath, 'utf-8');
  const lines = original.split('\n');

  const byLine = new Map<number, Finding>();
  for (const f of relevant) byLine.set(f.line, f);

  const providersToConfigure = new Map<string, ProviderSpec>();
  for (const f of relevant) providersToConfigure.set(f.provider.id, f.provider);

  // ── Drop stale VaultProof header block + any BASE_URL lines we manage ──
  const managedBaseUrlVars = new Set<string>();
  for (const p of providersToConfigure.values()) {
    if (p.base_url_env_var) managedBaseUrlVars.add(p.base_url_env_var);
  }
  managedBaseUrlVars.add('VAULTPROOF_PROJECT_ID');

  // ── Pass 1: swap key values on finding lines ──
  const swapped = lines.map((line, idx) => {
    const lineNo = idx + 1;
    const finding = byLine.get(lineNo);
    if (!finding) return line;
    return `${finding.varName}=${opts.projectId}`;
  });

  // ── Pass 2: drop stale managed vars so idempotent re-runs don't duplicate ──
  // Also drop any existing VaultProof header block.
  const cleaned: string[] = [];
  let inManagedBlock = false;
  for (const line of swapped) {
    if (line.startsWith('# ── VaultProof ──')) { inManagedBlock = true; continue; }
    if (inManagedBlock) {
      if (line.startsWith('# ────')) { inManagedBlock = false; continue; }
      if (line.startsWith('#') || line === '') continue;
      const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
      if (m && managedBaseUrlVars.has(m[1])) continue;
      inManagedBlock = false;
    }
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (m && managedBaseUrlVars.has(m[1])) continue;
    cleaned.push(line);
  }

  // ── Pass 3: prepend fresh VaultProof block ──
  const manualNotes: string[] = [];
  const header = buildHeader(opts, providersToConfigure, manualNotes);
  const result = header + '\n' + cleaned.join('\n');

  fs.writeFileSync(envPath, result);
  return { rewritten: relevant.length, backupPath: backup, manualNotes };
}

function buildHeader(
  opts: RewriteOptions,
  providers: Map<string, ProviderSpec>,
  manualNotes: string[],
): string {
  const out: string[] = [
    '# ── VaultProof ──────────────────────────────────────────────',
    '# One project ID for every protected key. Safe to commit.',
    '# Generated by `npx @vaultproof/init` — do not hand-edit values.',
    `VAULTPROOF_PROJECT_ID=${opts.projectId}`,
  ];
  for (const p of providers.values()) {
    if (p.base_url_env_var && p.base_url_path_suffix) {
      out.push(`${p.base_url_env_var}=${opts.proxyBaseUrl}${p.base_url_path_suffix}`);
    } else {
      manualNotes.push(
        `${p.label}: set your client's base URL to ${opts.proxyBaseUrl}/p/${p.id}`,
      );
    }
  }
  out.push('# ───────────────────────────────────────────────────────────');
  return out.join('\n');
}
