#!/usr/bin/env bash
set -euo pipefail

ENTERPRISE_HOSTNAME_VALUE="${ENTERPRISE_HOSTNAME:-enterprise.vaultproof.dev}"
ENTERPRISE_RUNTIME_TIER_VALUE="${ENTERPRISE_RUNTIME_TIER:-dedicated-production}"
EXECUTOR_BASE_URL_VALUE="${ENTERPRISE_EXECUTOR_BASE_URL:-http://127.0.0.1:3002}"
SIGNING_KEY_ID_VALUE="${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID:-enterprise-azure-v1}"
SIGNING_SECRET_VALUE="${ENTERPRISE_EXECUTOR_SIGNING_SECRET:-}"
AZURE_FRONT_DOOR_ID_VALUE="${ENTERPRISE_AZURE_FRONT_DOOR_ID:-}"
ORIGIN_LOCK_HEADER_NAME_VALUE="${ENTERPRISE_ORIGIN_LOCK_HEADER_NAME:-x-vaultproof-origin-lock}"
REQUIRE_ORIGIN_LOCK_VALUE="${ENTERPRISE_REQUIRE_ORIGIN_LOCK:-false}"
ORIGIN_LOCK_SECRET_VALUE="${ENTERPRISE_ORIGIN_LOCK_SECRET:-}"
SUPABASE_URL_VALUE="${SUPABASE_URL:-}"
SUPABASE_SERVICE_ROLE_KEY_VALUE="${SUPABASE_SERVICE_ROLE_KEY:-}"
MIXPANEL_TOKEN_VALUE="${ENTERPRISE_MIXPANEL_TOKEN:-}"
MIXPANEL_AUTOCAPTURE_VALUE="${ENTERPRISE_MIXPANEL_AUTOCAPTURE:-false}"
MIXPANEL_RECORD_SESSIONS_PERCENT_VALUE="${ENTERPRISE_MIXPANEL_RECORD_SESSIONS_PERCENT:-0}"
INTERNAL_ADMIN_HOSTNAME_VALUE="${VAULTPROOF_INTERNAL_ADMIN_HOSTNAME:-admin.vaultproof.dev}"
INTERNAL_ADMIN_PREVIEW_ENABLED_VALUE="${VAULTPROOF_INTERNAL_ADMIN_PREVIEW_ENABLED:-false}"
INTERNAL_ADMIN_EMAILS_VALUE="${VAULTPROOF_INTERNAL_ADMIN_EMAILS:-}"
INTERNAL_ADMIN_DOMAINS_VALUE="${VAULTPROOF_INTERNAL_ADMIN_DOMAINS:-}"
INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE="${VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED:-false}"
INTERNAL_ADMIN_APPROVAL_SECRET_VALUE="${VAULTPROOF_INTERNAL_ADMIN_APPROVAL_SECRET:-}"
ROTATED_SUPABASE_SERVICE_ROLE_AT_VALUE="${ROTATED_SUPABASE_SERVICE_ROLE_AT:-}"
ROTATED_EXECUTOR_SIGNING_SECRET_AT_VALUE="${ROTATED_EXECUTOR_SIGNING_SECRET_AT:-}"

cat <<EOF
PORT=3001
ENTERPRISE_HOSTNAME=${ENTERPRISE_HOSTNAME_VALUE}
ENTERPRISE_RUNTIME_TIER=${ENTERPRISE_RUNTIME_TIER_VALUE}
ENTERPRISE_EXECUTOR_BASE_URL=${EXECUTOR_BASE_URL_VALUE}
ENTERPRISE_EXECUTOR_SIGNING_KEY_ID=${SIGNING_KEY_ID_VALUE}
ENTERPRISE_EXECUTOR_SIGNING_SECRET=${SIGNING_SECRET_VALUE}
ENTERPRISE_AZURE_FRONT_DOOR_ID=${AZURE_FRONT_DOOR_ID_VALUE}
ENTERPRISE_ORIGIN_LOCK_HEADER_NAME=${ORIGIN_LOCK_HEADER_NAME_VALUE}
ENTERPRISE_REQUIRE_ORIGIN_LOCK=${REQUIRE_ORIGIN_LOCK_VALUE}
ENTERPRISE_ORIGIN_LOCK_SECRET=${ORIGIN_LOCK_SECRET_VALUE}
SUPABASE_URL=${SUPABASE_URL_VALUE}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY_VALUE}
ENTERPRISE_MIXPANEL_TOKEN=${MIXPANEL_TOKEN_VALUE}
ENTERPRISE_MIXPANEL_AUTOCAPTURE=${MIXPANEL_AUTOCAPTURE_VALUE}
ENTERPRISE_MIXPANEL_RECORD_SESSIONS_PERCENT=${MIXPANEL_RECORD_SESSIONS_PERCENT_VALUE}
VAULTPROOF_INTERNAL_ADMIN_HOSTNAME=${INTERNAL_ADMIN_HOSTNAME_VALUE}
VAULTPROOF_INTERNAL_ADMIN_PREVIEW_ENABLED=${INTERNAL_ADMIN_PREVIEW_ENABLED_VALUE}
VAULTPROOF_INTERNAL_ADMIN_EMAILS=${INTERNAL_ADMIN_EMAILS_VALUE}
VAULTPROOF_INTERNAL_ADMIN_DOMAINS=${INTERNAL_ADMIN_DOMAINS_VALUE}
VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED=${INTERNAL_ADMIN_ACTIONS_ENABLED_VALUE}
VAULTPROOF_INTERNAL_ADMIN_APPROVAL_SECRET=${INTERNAL_ADMIN_APPROVAL_SECRET_VALUE}
ROTATED_SUPABASE_SERVICE_ROLE_AT=${ROTATED_SUPABASE_SERVICE_ROLE_AT_VALUE}
ROTATED_EXECUTOR_SIGNING_SECRET_AT=${ROTATED_EXECUTOR_SIGNING_SECRET_AT_VALUE}
EOF

cat >&2 <<'EOF'

Review the generated control-plane env before installing it on the Confidential VM.
For the co-located production demo, keep ENTERPRISE_EXECUTOR_BASE_URL=http://127.0.0.1:3002.
Set ENTERPRISE_RUNTIME_TIER=shared-demo for shared demo infrastructure; keep dedicated-production for a customer-dedicated runtime.
Set ENTERPRISE_AZURE_FRONT_DOOR_ID to the Front Door profile's frontDoorId before requiring origin lock.
Set ENTERPRISE_MIXPANEL_TOKEN to enable enterprise page analytics. Autocapture/session recording stay off unless explicitly enabled.
Set VAULTPROOF_INTERNAL_ADMIN_EMAILS or VAULTPROOF_INTERNAL_ADMIN_DOMAINS before exposing admin.vaultproof.dev.
Keep VAULTPROOF_INTERNAL_ADMIN_ACTIONS_ENABLED=false unless the operator is intentionally enabling approval-gated employee write actions.
EOF
