#!/usr/bin/env bash
set -euo pipefail

ENTERPRISE_HOSTNAME_VALUE="${ENTERPRISE_HOSTNAME:-enterprise.vaultproof.dev}"
EXECUTOR_BASE_URL_VALUE="${ENTERPRISE_EXECUTOR_BASE_URL:-http://127.0.0.1:3002}"
SIGNING_KEY_ID_VALUE="${ENTERPRISE_EXECUTOR_SIGNING_KEY_ID:-enterprise-azure-v1}"
SIGNING_SECRET_VALUE="${ENTERPRISE_EXECUTOR_SIGNING_SECRET:-}"
AZURE_FRONT_DOOR_ID_VALUE="${ENTERPRISE_AZURE_FRONT_DOOR_ID:-}"
ORIGIN_LOCK_HEADER_NAME_VALUE="${ENTERPRISE_ORIGIN_LOCK_HEADER_NAME:-x-vaultproof-origin-lock}"
REQUIRE_ORIGIN_LOCK_VALUE="${ENTERPRISE_REQUIRE_ORIGIN_LOCK:-false}"
ORIGIN_LOCK_SECRET_VALUE="${ENTERPRISE_ORIGIN_LOCK_SECRET:-}"
SUPABASE_URL_VALUE="${SUPABASE_URL:-}"
SUPABASE_SERVICE_ROLE_KEY_VALUE="${SUPABASE_SERVICE_ROLE_KEY:-}"

cat <<EOF
PORT=3001
ENTERPRISE_HOSTNAME=${ENTERPRISE_HOSTNAME_VALUE}
ENTERPRISE_EXECUTOR_BASE_URL=${EXECUTOR_BASE_URL_VALUE}
ENTERPRISE_EXECUTOR_SIGNING_KEY_ID=${SIGNING_KEY_ID_VALUE}
ENTERPRISE_EXECUTOR_SIGNING_SECRET=${SIGNING_SECRET_VALUE}
ENTERPRISE_AZURE_FRONT_DOOR_ID=${AZURE_FRONT_DOOR_ID_VALUE}
ENTERPRISE_ORIGIN_LOCK_HEADER_NAME=${ORIGIN_LOCK_HEADER_NAME_VALUE}
ENTERPRISE_REQUIRE_ORIGIN_LOCK=${REQUIRE_ORIGIN_LOCK_VALUE}
ENTERPRISE_ORIGIN_LOCK_SECRET=${ORIGIN_LOCK_SECRET_VALUE}
SUPABASE_URL=${SUPABASE_URL_VALUE}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY_VALUE}
EOF

cat >&2 <<'EOF'

Review the generated control-plane env before installing it on the Confidential VM.
For the co-located production demo, keep ENTERPRISE_EXECUTOR_BASE_URL=http://127.0.0.1:3002.
Set ENTERPRISE_AZURE_FRONT_DOOR_ID to the Front Door profile's frontDoorId before requiring origin lock.
EOF
