/**
 * Noir ZK Proof Verification
 *
 * Verifies zero-knowledge proofs generated by the client widget
 * using the compiled key_auth Noir circuit and Barretenberg backend.
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Path to compiled circuit artifact
const CIRCUIT_PATH = join(__dirname, '..', '..', '..', 'circuits', 'target', 'key_auth.json');

let circuitLoaded = false;
let noir: any = null;
let backend: any = null;

/**
 * Lazily initialize the Noir verifier.
 * Loads the compiled circuit and creates a Barretenberg backend.
 */
async function initVerifier() {
  if (circuitLoaded) return;

  try {
    const circuitJson = JSON.parse(readFileSync(CIRCUIT_PATH, 'utf-8'));

    const { Noir } = await import('@noir-lang/noir_js');
    const { BarretenbergBackend } = await import('@noir-lang/backend_barretenberg');

    backend = new BarretenbergBackend(circuitJson);
    noir = new Noir(circuitJson);
    circuitLoaded = true;

    console.log('Noir proof verifier initialized');
  } catch (err) {
    console.warn('Could not initialize Noir verifier:', (err as Error).message);
    console.warn('Falling back to placeholder verification');
  }
}

export interface ProofPublicInputs {
  vaultCommitment: string;
  appIdHash: string;
  authorizedAppsRoot: string;
  treeDepth: number;
  nullifier: string;
}

/**
 * Verify a ZK proof against public inputs.
 *
 * Returns true if the proof is valid, false otherwise.
 * Falls back to placeholder verification if Noir is not available.
 */
export async function verifyProof(
  proofHex: string,
  publicInputs: ProofPublicInputs
): Promise<{ valid: boolean; reason?: string }> {
  await initVerifier();

  // If Noir verifier is available, use real verification
  if (circuitLoaded && backend) {
    try {
      const proofBytes = hexToBytes(proofHex);
      const isValid = await backend.verifyProof({
        proof: proofBytes,
        publicInputs: [
          publicInputs.vaultCommitment,
          publicInputs.appIdHash,
          publicInputs.authorizedAppsRoot,
          publicInputs.treeDepth.toString(),
          publicInputs.nullifier,
        ],
      });

      return { valid: isValid };
    } catch (err) {
      return { valid: false, reason: 'Proof verification failed' };
    }
  }

  // Placeholder: accept any non-empty proof string
  // This is the MVP fallback — real verification is above
  if (!proofHex || proofHex.length < 10) {
    return { valid: false, reason: 'Proof too short' };
  }

  return { valid: true, reason: 'placeholder-verification' };
}

/**
 * Generate a proof (server-side, for testing).
 * In production, proofs are generated client-side via WASM.
 */
export async function generateProof(
  privateInputs: Record<string, string>,
  publicInputs: Record<string, string>
): Promise<{ proof: string; publicInputs: string[] } | null> {
  await initVerifier();

  if (!circuitLoaded || !noir || !backend) {
    return null; // Can't generate without Noir
  }

  try {
    const inputs = { ...privateInputs, ...publicInputs };
    const { witness } = await noir.execute(inputs);
    const proof = await backend.generateProof(witness);

    return {
      proof: bytesToHex(proof.proof),
      publicInputs: proof.publicInputs,
    };
  } catch {
    return null;
  }
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}
