/**
 * Noir ZK Proof Verification
 *
 * Verifies zero-knowledge proofs generated by the client widget
 * using the compiled key_auth Noir circuit and Barretenberg backend.
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Path to compiled circuit artifact — try multiple locations
function findCircuitPath(): string {
  const candidates = [
    join(__dirname, '..', '..', '..', 'circuits', 'target', 'key_auth.json'),     // from dist/crypto/
    join(__dirname, '..', '..', '..', '..', 'circuits', 'target', 'key_auth.json'), // from src/crypto/
    join(process.cwd(), 'packages', 'circuits', 'target', 'key_auth.json'),         // from repo root
    join(process.cwd(), '..', 'circuits', 'target', 'key_auth.json'),               // from packages/backend/
  ];
  for (const p of candidates) {
    try {
      readFileSync(p);
      return p;
    } catch {}
  }
  return candidates[0]; // Default, will fail gracefully in initVerifier
}
const CIRCUIT_PATH = findCircuitPath();

let circuitLoaded = false;
let noir: any = null;
let backend: any = null;

/**
 * Lazily initialize the Noir verifier.
 * Loads the compiled circuit and creates a Barretenberg backend.
 */
async function initVerifier() {
  if (circuitLoaded) return;

  try {
    const circuitJson = JSON.parse(readFileSync(CIRCUIT_PATH, 'utf-8'));

    const { Noir } = await import('@noir-lang/noir_js');
    const { BarretenbergBackend } = await import('@noir-lang/backend_barretenberg');

    backend = new BarretenbergBackend(circuitJson);
    noir = new Noir(circuitJson);
    circuitLoaded = true;

    console.log('Noir proof verifier initialized');
  } catch (err) {
    const isProduction = process.env.NODE_ENV === 'production';
    const requireReal = process.env.REQUIRE_REAL_PROOFS === 'true';
    if (isProduction || requireReal) {
      console.error('CRITICAL: Noir proof verifier failed to load in production:', (err as Error).message);
      console.error('CRITICAL: All ZK proof verifications will be rejected. Set REQUIRE_REAL_PROOFS=true to enforce.');
      if (requireReal) {
        // Hard fail — don't allow the server to silently accept unverified proofs
        throw new Error(`Noir verifier required but failed to initialize: ${(err as Error).message}`);
      }
    } else {
      console.warn('Could not initialize Noir verifier:', (err as Error).message);
      console.warn('Falling back to placeholder verification');
    }
  }
}

/**
 * Warm up the Noir verifier at server startup.
 * In production, this will throw if REQUIRE_REAL_PROOFS=true and circuit fails to load.
 */
export async function warmupVerifier(): Promise<void> {
  await initVerifier();
}

export interface ProofPublicInputs {
  vaultCommitment: string;
  appIdHash: string;
  authorizedAppsRoot: string;
  treeDepth: number;
  nullifier: string;
}

/**
 * Verify a ZK proof against public inputs.
 *
 * Returns true if the proof is valid, false otherwise.
 * Falls back to placeholder verification if Noir is not available.
 */
export async function verifyProof(
  proofHex: string,
  publicInputs: ProofPublicInputs
): Promise<{ valid: boolean; reason?: string }> {
  await initVerifier();

  // If Noir verifier is available, use real verification
  if (circuitLoaded && backend) {
    try {
      const proofBytes = hexToBytes(proofHex);
      const isValid = await backend.verifyProof({
        proof: proofBytes,
        publicInputs: [
          publicInputs.vaultCommitment,
          publicInputs.appIdHash,
          publicInputs.authorizedAppsRoot,
          publicInputs.treeDepth.toString(),
          publicInputs.nullifier,
        ],
      });

      return { valid: isValid };
    } catch (err) {
      return { valid: false, reason: 'Proof verification failed' };
    }
  }

  // Placeholder fallback — controlled by env var
  if (process.env.REQUIRE_REAL_PROOFS === 'true') {
    return { valid: false, reason: 'Real proof required but Noir verifier not available' };
  }

  // MVP fallback: accept non-empty proof strings
  if (!proofHex || proofHex.length < 10) {
    return { valid: false, reason: 'Proof too short' };
  }

  return { valid: true, reason: 'placeholder-verification' };
}

/**
 * Generate a proof (server-side, for testing).
 * In production, proofs are generated client-side via WASM.
 */
export async function generateProof(
  privateInputs: Record<string, string>,
  publicInputs: Record<string, string>
): Promise<{ proof: string; publicInputs: string[] } | null> {
  await initVerifier();

  if (!circuitLoaded || !noir || !backend) {
    return null; // Can't generate without Noir
  }

  try {
    const inputs = { ...privateInputs, ...publicInputs };
    const { witness } = await noir.execute(inputs);
    const proof = await backend.generateProof(witness);

    return {
      proof: bytesToHex(proof.proof),
      publicInputs: proof.publicInputs,
    };
  } catch {
    return null;
  }
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}
